//! zc-codex-protocol: Rust types for the Codex app-server protocol (`codex app-server`, NDJSON
//! JSON-RPC without the `jsonrpc` field).
//!
//! Generated by `code/scripts/gen-rust-codex-protocol.ts` from the JSON Schemas of
//! `openai/codex@fe74a774532af67b5a4a3dec03ce9469e17f89af`
//! (`codex-rs/app-server-protocol/schema`), the commit `effect-codex-app-server` pins
//! ([`methods::UPSTREAM_REF`]). See docs/zenith-code/codex.md.
//!
//! - [`types`]: every definition reachable from the server notifications, the server requests,
//!   the client requests zenith code sends and `initialized`.
//! - [`methods`]: method names, [`ServerNotification`] / [`ServerRequest`] (decode by method),
//!   the response type of each server request, and [`ClientRequest`] markers.
//!
//! Unknown enum values and union members are tolerated (`Unknown(...)` / `Other(...)`), so a
//! newer `codex` adding a plan slug or an item type does not fail a whole message.

pub mod methods;
pub mod serde_helpers;
pub mod types;

pub use methods::{client_requests, names, server_responses, ClientRequest, ServerNotification, ServerRequest};
pub use types::*;

use serde::{Deserialize, Deserializer, Serialize, Serializer};

/// A JSON `number`: an `f64` written like JavaScript writes it (integral values without a
/// fractional part), so a decoded-then-encoded payload keeps its numbers as they were.
#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Default)]
pub struct Number(pub f64);

impl Number {
    #[must_use]
    pub const fn get(self) -> f64 {
        self.0
    }
}

impl From<f64> for Number {
    fn from(value: f64) -> Self {
        Self(value)
    }
}

/// 2^53: integers up to it are exact in an `f64`.
const MAX_SAFE: f64 = 9_007_199_254_740_992.0;

impl Serialize for Number {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        let value = self.0;
        if value.is_finite() && value.fract() == 0.0 && value.abs() <= MAX_SAFE {
            #[allow(clippy::cast_possible_truncation)]
            return serializer.serialize_i64(value as i64);
        }
        serializer.serialize_f64(value)
    }
}

impl<'de> Deserialize<'de> for Number {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        f64::deserialize(deserializer).map(Number)
    }
}

/// Serde for the generated string enums: written as their wire string; any string is read
/// (unknown ones land in `Unknown`).
#[doc(hidden)]
#[macro_export]
macro_rules! string_enum_serde {
    ($name:ident) => {
        impl ::serde::Serialize for $name {
            fn serialize<S: ::serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
                serializer.serialize_str(self.as_str())
            }
        }
        impl<'de> ::serde::Deserialize<'de> for $name {
            fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
                let value = <::std::borrow::Cow<'de, str> as ::serde::Deserialize>::deserialize(deserializer)?;
                Ok($name::from_wire(&value))
            }
        }
        impl ::std::fmt::Display for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str(self.as_str())
            }
        }
        impl Default for $name {
            fn default() -> Self {
                $name::Unknown(String::new())
            }
        }
    };
}

#[cfg(test)]
mod tests;
