// This file is generated by code/scripts/gen-rust-codex-protocol.ts. Do not edit by hand.
// Upstream protocol: openai/codex@fe74a774532af67b5a4a3dec03ce9469e17f89af (codex-rs/app-server-protocol/schema).

use serde::Serialize;

#[allow(unused_imports)]
use crate::types::*;

/// The upstream commit the types follow.
pub const UPSTREAM_REF: &str = "fe74a774532af67b5a4a3dec03ce9469e17f89af";

/// Method name constants.
pub mod names {
    pub const ERROR: &str = "error";
    pub const THREAD_STARTED: &str = "thread/started";
    pub const THREAD_STATUS_CHANGED: &str = "thread/status/changed";
    pub const THREAD_ARCHIVED: &str = "thread/archived";
    pub const THREAD_DELETED: &str = "thread/deleted";
    pub const THREAD_UNARCHIVED: &str = "thread/unarchived";
    pub const THREAD_CLOSED: &str = "thread/closed";
    pub const THREAD_REVERTED: &str = "thread/reverted";
    pub const SKILLS_CHANGED: &str = "skills/changed";
    pub const THREAD_NAME_UPDATED: &str = "thread/name/updated";
    pub const THREAD_ATTACHMENT_UPDATED: &str = "thread/attachment/updated";
    pub const THREAD_GOAL_UPDATED: &str = "thread/goal/updated";
    pub const THREAD_GOAL_CLEARED: &str = "thread/goal/cleared";
    pub const THREAD_QUEUE_CHANGED: &str = "thread/queue/changed";
    pub const PROJECT_CHANGED: &str = "project/changed";
    pub const THREAD_PROJECT_UPDATED: &str = "thread/project/updated";
    pub const THREAD_ENVIRONMENT_CONNECTED: &str = "thread/environment/connected";
    pub const THREAD_ENVIRONMENT_DISCONNECTED: &str = "thread/environment/disconnected";
    pub const THREAD_SETTINGS_UPDATED: &str = "thread/settings/updated";
    pub const THREAD_TOKEN_USAGE_UPDATED: &str = "thread/tokenUsage/updated";
    pub const TURN_STARTED: &str = "turn/started";
    pub const HOOK_STARTED: &str = "hook/started";
    pub const TURN_COMPLETED: &str = "turn/completed";
    pub const HOOK_COMPLETED: &str = "hook/completed";
    pub const TURN_DIFF_UPDATED: &str = "turn/diff/updated";
    pub const TURN_PLAN_UPDATED: &str = "turn/plan/updated";
    pub const ITEM_STARTED: &str = "item/started";
    pub const ITEM_AUTO_APPROVAL_REVIEW_STARTED: &str = "item/autoApprovalReview/started";
    pub const ITEM_AUTO_APPROVAL_REVIEW_COMPLETED: &str = "item/autoApprovalReview/completed";
    pub const AUTO_APPROVAL_REVIEW_STRICT_REVIEW_REQUIRED: &str = "autoApprovalReview/strictReviewRequired";
    pub const ITEM_COMPLETED: &str = "item/completed";
    pub const RAW_RESPONSE_ITEM_COMPLETED: &str = "rawResponseItem/completed";
    pub const RAW_RESPONSE_COMPLETED: &str = "rawResponse/completed";
    pub const ITEM_AGENT_MESSAGE_DELTA: &str = "item/agentMessage/delta";
    pub const ITEM_PLAN_DELTA: &str = "item/plan/delta";
    pub const COMMAND_EXEC_OUTPUT_DELTA: &str = "command/exec/outputDelta";
    pub const PROCESS_OUTPUT_DELTA: &str = "process/outputDelta";
    pub const PROCESS_EXITED: &str = "process/exited";
    pub const ITEM_COMMAND_EXECUTION_OUTPUT_DELTA: &str = "item/commandExecution/outputDelta";
    pub const ITEM_COMMAND_EXECUTION_TERMINAL_INTERACTION: &str = "item/commandExecution/terminalInteraction";
    pub const ITEM_FILE_CHANGE_OUTPUT_DELTA: &str = "item/fileChange/outputDelta";
    pub const ITEM_FILE_CHANGE_PATCH_UPDATED: &str = "item/fileChange/patchUpdated";
    pub const SERVER_REQUEST_RESOLVED: &str = "serverRequest/resolved";
    pub const ITEM_MCP_TOOL_CALL_PROGRESS: &str = "item/mcpToolCall/progress";
    pub const MCP_SERVER_OAUTH_LOGIN_COMPLETED: &str = "mcpServer/oauthLogin/completed";
    pub const MCP_SERVER_STARTUP_STATUS_UPDATED: &str = "mcpServer/startupStatus/updated";
    pub const MCP_SERVER_EVENT_STREAM_NOTIFICATION: &str = "mcpServer/event/stream/notification";
    pub const ACCOUNT_UPDATED: &str = "account/updated";
    pub const ACCOUNT_RATE_LIMITS_UPDATED: &str = "account/rateLimits/updated";
    pub const APP_LIST_UPDATED: &str = "app/list/updated";
    pub const REMOTE_CONTROL_STATUS_CHANGED: &str = "remoteControl/status/changed";
    pub const EXTERNAL_AGENT_CONFIG_IMPORT_PROGRESS: &str = "externalAgentConfig/import/progress";
    pub const EXTERNAL_AGENT_CONFIG_IMPORT_COMPLETED: &str = "externalAgentConfig/import/completed";
    pub const FS_CHANGED: &str = "fs/changed";
    pub const ITEM_REASONING_SUMMARY_TEXT_DELTA: &str = "item/reasoning/summaryTextDelta";
    pub const ITEM_REASONING_SUMMARY_PART_ADDED: &str = "item/reasoning/summaryPartAdded";
    pub const ITEM_REASONING_TEXT_DELTA: &str = "item/reasoning/textDelta";
    pub const THREAD_COMPACTED: &str = "thread/compacted";
    pub const MODEL_REROUTED: &str = "model/rerouted";
    pub const MODEL_VERIFICATION: &str = "model/verification";
    pub const MODEL_PROVIDER_AUTH_RECOVERY_STARTED: &str = "modelProvider/authRecoveryStarted";
    pub const MODEL_PROVIDER_AUTH_RECOVERY_COMPLETED: &str = "modelProvider/authRecoveryCompleted";
    pub const TURN_MODERATION_METADATA: &str = "turn/moderationMetadata";
    pub const MODEL_SAFETY_BUFFERING_UPDATED: &str = "model/safetyBuffering/updated";
    pub const WARNING: &str = "warning";
    pub const GUARDIAN_WARNING: &str = "guardianWarning";
    pub const DEPRECATION_NOTICE: &str = "deprecationNotice";
    pub const CONFIG_WARNING: &str = "configWarning";
    pub const FUZZY_FILE_SEARCH_SESSION_UPDATED: &str = "fuzzyFileSearch/sessionUpdated";
    pub const FUZZY_FILE_SEARCH_SESSION_COMPLETED: &str = "fuzzyFileSearch/sessionCompleted";
    pub const THREAD_REALTIME_STARTED: &str = "thread/realtime/started";
    pub const THREAD_REALTIME_ITEM_ADDED: &str = "thread/realtime/itemAdded";
    pub const THREAD_REALTIME_ITEM_STARTED: &str = "thread/realtime/item/started";
    pub const THREAD_REALTIME_ITEM_TRANSCRIPT_DELTA: &str = "thread/realtime/item/transcript/delta";
    pub const THREAD_REALTIME_ITEM_COMPLETED: &str = "thread/realtime/item/completed";
    pub const THREAD_REALTIME_TRANSCRIPT_DELTA: &str = "thread/realtime/transcript/delta";
    pub const THREAD_REALTIME_TRANSCRIPT_DONE: &str = "thread/realtime/transcript/done";
    pub const THREAD_REALTIME_OUTPUT_AUDIO_DELTA: &str = "thread/realtime/outputAudio/delta";
    pub const THREAD_REALTIME_SDP: &str = "thread/realtime/sdp";
    pub const THREAD_REALTIME_ERROR: &str = "thread/realtime/error";
    pub const THREAD_REALTIME_CLOSED: &str = "thread/realtime/closed";
    pub const WINDOWS_WORLD_WRITABLE_WARNING: &str = "windows/worldWritableWarning";
    pub const WINDOWS_SANDBOX_SETUP_COMPLETED: &str = "windowsSandbox/setupCompleted";
    pub const ACCOUNT_LOGIN_COMPLETED: &str = "account/login/completed";
    pub const ITEM_COMMAND_EXECUTION_REQUEST_APPROVAL: &str = "item/commandExecution/requestApproval";
    pub const ITEM_FILE_CHANGE_REQUEST_APPROVAL: &str = "item/fileChange/requestApproval";
    pub const ITEM_TOOL_REQUEST_USER_INPUT: &str = "item/tool/requestUserInput";
    pub const MCP_SERVER_ELICITATION_REQUEST: &str = "mcpServer/elicitation/request";
    pub const ITEM_PERMISSIONS_REQUEST_APPROVAL: &str = "item/permissions/requestApproval";
    pub const ITEM_TOOL_CALL: &str = "item/tool/call";
    pub const ACCOUNT_CHATGPT_AUTH_TOKENS_REFRESH: &str = "account/chatgptAuthTokens/refresh";
    pub const ATTESTATION_GENERATE: &str = "attestation/generate";
    pub const APPLY_PATCH_APPROVAL: &str = "applyPatchApproval";
    pub const EXEC_COMMAND_APPROVAL: &str = "execCommandApproval";
    pub const INITIALIZE: &str = "initialize";
    pub const THREAD_START: &str = "thread/start";
    pub const THREAD_RESUME: &str = "thread/resume";
    pub const THREAD_READ: &str = "thread/read";
    pub const THREAD_TURNS_LIST: &str = "thread/turns/list";
    pub const THREAD_REVERT: &str = "thread/revert";
    pub const THREAD_INJECT_ITEMS: &str = "thread/inject_items";
    pub const THREAD_COMPACT_START: &str = "thread/compact/start";
    pub const TURN_START: &str = "turn/start";
    pub const TURN_INTERRUPT: &str = "turn/interrupt";
    pub const CONFIG_MCP_SERVER_RELOAD: &str = "config/mcpServer/reload";
    pub const FEEDBACK_UPLOAD: &str = "feedback/upload";
    pub const ACCOUNT_READ: &str = "account/read";
    pub const ACCOUNT_RATE_LIMITS_READ: &str = "account/rateLimits/read";
    pub const ACCOUNT_RATE_LIMIT_RESET_CREDIT_CONSUME: &str = "account/rateLimitResetCredit/consume";
    pub const MODEL_LIST: &str = "model/list";
    pub const SKILLS_LIST: &str = "skills/list";
    pub const INITIALIZED: &str = "initialized";
}

pub const SERVER_NOTIFICATION_METHODS: &[&str] = &[
    "error",
    "thread/started",
    "thread/status/changed",
    "thread/archived",
    "thread/deleted",
    "thread/unarchived",
    "thread/closed",
    "thread/reverted",
    "skills/changed",
    "thread/name/updated",
    "thread/attachment/updated",
    "thread/goal/updated",
    "thread/goal/cleared",
    "thread/queue/changed",
    "project/changed",
    "thread/project/updated",
    "thread/environment/connected",
    "thread/environment/disconnected",
    "thread/settings/updated",
    "thread/tokenUsage/updated",
    "turn/started",
    "hook/started",
    "turn/completed",
    "hook/completed",
    "turn/diff/updated",
    "turn/plan/updated",
    "item/started",
    "item/autoApprovalReview/started",
    "item/autoApprovalReview/completed",
    "autoApprovalReview/strictReviewRequired",
    "item/completed",
    "rawResponseItem/completed",
    "rawResponse/completed",
    "item/agentMessage/delta",
    "item/plan/delta",
    "command/exec/outputDelta",
    "process/outputDelta",
    "process/exited",
    "item/commandExecution/outputDelta",
    "item/commandExecution/terminalInteraction",
    "item/fileChange/outputDelta",
    "item/fileChange/patchUpdated",
    "serverRequest/resolved",
    "item/mcpToolCall/progress",
    "mcpServer/oauthLogin/completed",
    "mcpServer/startupStatus/updated",
    "mcpServer/event/stream/notification",
    "account/updated",
    "account/rateLimits/updated",
    "app/list/updated",
    "remoteControl/status/changed",
    "externalAgentConfig/import/progress",
    "externalAgentConfig/import/completed",
    "fs/changed",
    "item/reasoning/summaryTextDelta",
    "item/reasoning/summaryPartAdded",
    "item/reasoning/textDelta",
    "thread/compacted",
    "model/rerouted",
    "model/verification",
    "modelProvider/authRecoveryStarted",
    "modelProvider/authRecoveryCompleted",
    "turn/moderationMetadata",
    "model/safetyBuffering/updated",
    "warning",
    "guardianWarning",
    "deprecationNotice",
    "configWarning",
    "fuzzyFileSearch/sessionUpdated",
    "fuzzyFileSearch/sessionCompleted",
    "thread/realtime/started",
    "thread/realtime/itemAdded",
    "thread/realtime/item/started",
    "thread/realtime/item/transcript/delta",
    "thread/realtime/item/completed",
    "thread/realtime/transcript/delta",
    "thread/realtime/transcript/done",
    "thread/realtime/outputAudio/delta",
    "thread/realtime/sdp",
    "thread/realtime/error",
    "thread/realtime/closed",
    "windows/worldWritableWarning",
    "windowsSandbox/setupCompleted",
    "account/login/completed",
];

pub const SERVER_REQUEST_METHODS: &[&str] = &[
    "item/commandExecution/requestApproval",
    "item/fileChange/requestApproval",
    "item/tool/requestUserInput",
    "mcpServer/elicitation/request",
    "item/permissions/requestApproval",
    "item/tool/call",
    "account/chatgptAuthTokens/refresh",
    "attestation/generate",
    "applyPatchApproval",
    "execCommandApproval",
];

pub const CLIENT_NOTIFICATION_METHODS: &[&str] = &["initialized"];

pub const CLIENT_REQUEST_METHODS_USED: &[&str] = &[
    "initialize",
    "thread/start",
    "thread/resume",
    "thread/read",
    "thread/turns/list",
    "thread/revert",
    "thread/inject_items",
    "thread/compact/start",
    "turn/start",
    "turn/interrupt",
    "config/mcpServer/reload",
    "feedback/upload",
    "account/read",
    "account/rateLimits/read",
    "account/rateLimitResetCredit/consume",
    "model/list",
    "skills/list",
];

/// A decoded server notification: one variant per method of the pinned protocol.
#[derive(Debug, Clone, PartialEq)]
pub enum ServerNotification {
    Error(ErrorNotification),
    ThreadStarted(ThreadStartedNotification),
    ThreadStatusChanged(ThreadStatusChangedNotification),
    ThreadArchived(ThreadArchivedNotification),
    ThreadDeleted(ThreadDeletedNotification),
    ThreadUnarchived(ThreadUnarchivedNotification),
    ThreadClosed(ThreadClosedNotification),
    ThreadReverted(ThreadRevertedNotification),
    SkillsChanged(SkillsChangedNotification),
    ThreadNameUpdated(ThreadNameUpdatedNotification),
    ThreadAttachmentUpdated(ThreadAttachmentUpdatedNotification),
    ThreadGoalUpdated(ThreadGoalUpdatedNotification),
    ThreadGoalCleared(ThreadGoalClearedNotification),
    ThreadQueueChanged(ThreadQueueChangedNotification),
    ProjectChanged(ProjectChangedNotification),
    ThreadProjectUpdated(ThreadProjectUpdatedNotification),
    ThreadEnvironmentConnected(EnvironmentConnectionNotification),
    ThreadEnvironmentDisconnected(EnvironmentConnectionNotification),
    ThreadSettingsUpdated(ThreadSettingsUpdatedNotification),
    ThreadTokenUsageUpdated(ThreadTokenUsageUpdatedNotification),
    TurnStarted(TurnStartedNotification),
    HookStarted(HookStartedNotification),
    TurnCompleted(TurnCompletedNotification),
    HookCompleted(HookCompletedNotification),
    TurnDiffUpdated(TurnDiffUpdatedNotification),
    TurnPlanUpdated(TurnPlanUpdatedNotification),
    ItemStarted(ItemStartedNotification),
    ItemAutoApprovalReviewStarted(ItemGuardianApprovalReviewStartedNotification),
    ItemAutoApprovalReviewCompleted(ItemGuardianApprovalReviewCompletedNotification),
    AutoApprovalReviewStrictReviewRequired(StrictReviewRequiredNotification),
    ItemCompleted(ItemCompletedNotification),
    RawResponseItemCompleted(RawResponseItemCompletedNotification),
    RawResponseCompleted(RawResponseCompletedNotification),
    ItemAgentMessageDelta(AgentMessageDeltaNotification),
    ItemPlanDelta(PlanDeltaNotification),
    CommandExecOutputDelta(CommandExecOutputDeltaNotification),
    ProcessOutputDelta(ProcessOutputDeltaNotification),
    ProcessExited(ProcessExitedNotification),
    ItemCommandExecutionOutputDelta(CommandExecutionOutputDeltaNotification),
    ItemCommandExecutionTerminalInteraction(TerminalInteractionNotification),
    ItemFileChangeOutputDelta(FileChangeOutputDeltaNotification),
    ItemFileChangePatchUpdated(FileChangePatchUpdatedNotification),
    ServerRequestResolved(ServerRequestResolvedNotification),
    ItemMcpToolCallProgress(McpToolCallProgressNotification),
    McpServerOauthLoginCompleted(McpServerOauthLoginCompletedNotification),
    McpServerStartupStatusUpdated(McpServerStatusUpdatedNotification),
    McpServerEventStreamNotification(McpServerEventStreamNotification),
    AccountUpdated(AccountUpdatedNotification),
    AccountRateLimitsUpdated(AccountRateLimitsUpdatedNotification),
    AppListUpdated(AppListUpdatedNotification),
    RemoteControlStatusChanged(RemoteControlStatusChangedNotification),
    ExternalAgentConfigImportProgress(ExternalAgentConfigImportProgressNotification),
    ExternalAgentConfigImportCompleted(ExternalAgentConfigImportCompletedNotification),
    FsChanged(FsChangedNotification),
    ItemReasoningSummaryTextDelta(ReasoningSummaryTextDeltaNotification),
    ItemReasoningSummaryPartAdded(ReasoningSummaryPartAddedNotification),
    ItemReasoningTextDelta(ReasoningTextDeltaNotification),
    ThreadCompacted(ContextCompactedNotification),
    ModelRerouted(ModelReroutedNotification),
    ModelVerification(ModelVerificationNotification),
    ModelProviderAuthRecoveryStarted(AuthRecoveryNotification),
    ModelProviderAuthRecoveryCompleted(AuthRecoveryNotification),
    TurnModerationMetadata(TurnModerationMetadataNotification),
    ModelSafetyBufferingUpdated(ModelSafetyBufferingUpdatedNotification),
    Warning(WarningNotification),
    GuardianWarning(GuardianWarningNotification),
    DeprecationNotice(DeprecationNoticeNotification),
    ConfigWarning(ConfigWarningNotification),
    FuzzyFileSearchSessionUpdated(FuzzyFileSearchSessionUpdatedNotification),
    FuzzyFileSearchSessionCompleted(FuzzyFileSearchSessionCompletedNotification),
    ThreadRealtimeStarted(ThreadRealtimeStartedNotification),
    ThreadRealtimeItemAdded(ThreadRealtimeItemAddedNotification),
    ThreadRealtimeItemStarted(ThreadRealtimeItemStartedNotification),
    ThreadRealtimeItemTranscriptDelta(ThreadRealtimeItemTranscriptDeltaNotification),
    ThreadRealtimeItemCompleted(ThreadRealtimeItemCompletedNotification),
    ThreadRealtimeTranscriptDelta(ThreadRealtimeTranscriptDeltaNotification),
    ThreadRealtimeTranscriptDone(ThreadRealtimeTranscriptDoneNotification),
    ThreadRealtimeOutputAudioDelta(ThreadRealtimeOutputAudioDeltaNotification),
    ThreadRealtimeSdp(ThreadRealtimeSdpNotification),
    ThreadRealtimeError(ThreadRealtimeErrorNotification),
    ThreadRealtimeClosed(ThreadRealtimeClosedNotification),
    WindowsWorldWritableWarning(WindowsWorldWritableWarningNotification),
    WindowsSandboxSetupCompleted(WindowsSandboxSetupCompletedNotification),
    AccountLoginCompleted(AccountLoginCompletedNotification),
}

impl ServerNotification {
    pub fn method(&self) -> &'static str {
        match self {
            ServerNotification::Error(_) => "error",
            ServerNotification::ThreadStarted(_) => "thread/started",
            ServerNotification::ThreadStatusChanged(_) => "thread/status/changed",
            ServerNotification::ThreadArchived(_) => "thread/archived",
            ServerNotification::ThreadDeleted(_) => "thread/deleted",
            ServerNotification::ThreadUnarchived(_) => "thread/unarchived",
            ServerNotification::ThreadClosed(_) => "thread/closed",
            ServerNotification::ThreadReverted(_) => "thread/reverted",
            ServerNotification::SkillsChanged(_) => "skills/changed",
            ServerNotification::ThreadNameUpdated(_) => "thread/name/updated",
            ServerNotification::ThreadAttachmentUpdated(_) => "thread/attachment/updated",
            ServerNotification::ThreadGoalUpdated(_) => "thread/goal/updated",
            ServerNotification::ThreadGoalCleared(_) => "thread/goal/cleared",
            ServerNotification::ThreadQueueChanged(_) => "thread/queue/changed",
            ServerNotification::ProjectChanged(_) => "project/changed",
            ServerNotification::ThreadProjectUpdated(_) => "thread/project/updated",
            ServerNotification::ThreadEnvironmentConnected(_) => "thread/environment/connected",
            ServerNotification::ThreadEnvironmentDisconnected(_) => "thread/environment/disconnected",
            ServerNotification::ThreadSettingsUpdated(_) => "thread/settings/updated",
            ServerNotification::ThreadTokenUsageUpdated(_) => "thread/tokenUsage/updated",
            ServerNotification::TurnStarted(_) => "turn/started",
            ServerNotification::HookStarted(_) => "hook/started",
            ServerNotification::TurnCompleted(_) => "turn/completed",
            ServerNotification::HookCompleted(_) => "hook/completed",
            ServerNotification::TurnDiffUpdated(_) => "turn/diff/updated",
            ServerNotification::TurnPlanUpdated(_) => "turn/plan/updated",
            ServerNotification::ItemStarted(_) => "item/started",
            ServerNotification::ItemAutoApprovalReviewStarted(_) => "item/autoApprovalReview/started",
            ServerNotification::ItemAutoApprovalReviewCompleted(_) => "item/autoApprovalReview/completed",
            ServerNotification::AutoApprovalReviewStrictReviewRequired(_) => "autoApprovalReview/strictReviewRequired",
            ServerNotification::ItemCompleted(_) => "item/completed",
            ServerNotification::RawResponseItemCompleted(_) => "rawResponseItem/completed",
            ServerNotification::RawResponseCompleted(_) => "rawResponse/completed",
            ServerNotification::ItemAgentMessageDelta(_) => "item/agentMessage/delta",
            ServerNotification::ItemPlanDelta(_) => "item/plan/delta",
            ServerNotification::CommandExecOutputDelta(_) => "command/exec/outputDelta",
            ServerNotification::ProcessOutputDelta(_) => "process/outputDelta",
            ServerNotification::ProcessExited(_) => "process/exited",
            ServerNotification::ItemCommandExecutionOutputDelta(_) => "item/commandExecution/outputDelta",
            ServerNotification::ItemCommandExecutionTerminalInteraction(_) => "item/commandExecution/terminalInteraction",
            ServerNotification::ItemFileChangeOutputDelta(_) => "item/fileChange/outputDelta",
            ServerNotification::ItemFileChangePatchUpdated(_) => "item/fileChange/patchUpdated",
            ServerNotification::ServerRequestResolved(_) => "serverRequest/resolved",
            ServerNotification::ItemMcpToolCallProgress(_) => "item/mcpToolCall/progress",
            ServerNotification::McpServerOauthLoginCompleted(_) => "mcpServer/oauthLogin/completed",
            ServerNotification::McpServerStartupStatusUpdated(_) => "mcpServer/startupStatus/updated",
            ServerNotification::McpServerEventStreamNotification(_) => "mcpServer/event/stream/notification",
            ServerNotification::AccountUpdated(_) => "account/updated",
            ServerNotification::AccountRateLimitsUpdated(_) => "account/rateLimits/updated",
            ServerNotification::AppListUpdated(_) => "app/list/updated",
            ServerNotification::RemoteControlStatusChanged(_) => "remoteControl/status/changed",
            ServerNotification::ExternalAgentConfigImportProgress(_) => "externalAgentConfig/import/progress",
            ServerNotification::ExternalAgentConfigImportCompleted(_) => "externalAgentConfig/import/completed",
            ServerNotification::FsChanged(_) => "fs/changed",
            ServerNotification::ItemReasoningSummaryTextDelta(_) => "item/reasoning/summaryTextDelta",
            ServerNotification::ItemReasoningSummaryPartAdded(_) => "item/reasoning/summaryPartAdded",
            ServerNotification::ItemReasoningTextDelta(_) => "item/reasoning/textDelta",
            ServerNotification::ThreadCompacted(_) => "thread/compacted",
            ServerNotification::ModelRerouted(_) => "model/rerouted",
            ServerNotification::ModelVerification(_) => "model/verification",
            ServerNotification::ModelProviderAuthRecoveryStarted(_) => "modelProvider/authRecoveryStarted",
            ServerNotification::ModelProviderAuthRecoveryCompleted(_) => "modelProvider/authRecoveryCompleted",
            ServerNotification::TurnModerationMetadata(_) => "turn/moderationMetadata",
            ServerNotification::ModelSafetyBufferingUpdated(_) => "model/safetyBuffering/updated",
            ServerNotification::Warning(_) => "warning",
            ServerNotification::GuardianWarning(_) => "guardianWarning",
            ServerNotification::DeprecationNotice(_) => "deprecationNotice",
            ServerNotification::ConfigWarning(_) => "configWarning",
            ServerNotification::FuzzyFileSearchSessionUpdated(_) => "fuzzyFileSearch/sessionUpdated",
            ServerNotification::FuzzyFileSearchSessionCompleted(_) => "fuzzyFileSearch/sessionCompleted",
            ServerNotification::ThreadRealtimeStarted(_) => "thread/realtime/started",
            ServerNotification::ThreadRealtimeItemAdded(_) => "thread/realtime/itemAdded",
            ServerNotification::ThreadRealtimeItemStarted(_) => "thread/realtime/item/started",
            ServerNotification::ThreadRealtimeItemTranscriptDelta(_) => "thread/realtime/item/transcript/delta",
            ServerNotification::ThreadRealtimeItemCompleted(_) => "thread/realtime/item/completed",
            ServerNotification::ThreadRealtimeTranscriptDelta(_) => "thread/realtime/transcript/delta",
            ServerNotification::ThreadRealtimeTranscriptDone(_) => "thread/realtime/transcript/done",
            ServerNotification::ThreadRealtimeOutputAudioDelta(_) => "thread/realtime/outputAudio/delta",
            ServerNotification::ThreadRealtimeSdp(_) => "thread/realtime/sdp",
            ServerNotification::ThreadRealtimeError(_) => "thread/realtime/error",
            ServerNotification::ThreadRealtimeClosed(_) => "thread/realtime/closed",
            ServerNotification::WindowsWorldWritableWarning(_) => "windows/worldWritableWarning",
            ServerNotification::WindowsSandboxSetupCompleted(_) => "windowsSandbox/setupCompleted",
            ServerNotification::AccountLoginCompleted(_) => "account/login/completed",
        }
    }

    /// Decodes `params` for a known `method`: `None` when the method is not part of the
    /// protocol, `Some(Err)` when the params do not match its schema (TS drops those).
    pub fn decode(method: &str, params: Option<serde_json::Value>) -> Option<Result<Self, serde_json::Error>> {
        let params = params.unwrap_or(serde_json::Value::Null);
        Some(match method {
            "error" => serde_json::from_value(params).map(ServerNotification::Error),
            "thread/started" => serde_json::from_value(params).map(ServerNotification::ThreadStarted),
            "thread/status/changed" => serde_json::from_value(params).map(ServerNotification::ThreadStatusChanged),
            "thread/archived" => serde_json::from_value(params).map(ServerNotification::ThreadArchived),
            "thread/deleted" => serde_json::from_value(params).map(ServerNotification::ThreadDeleted),
            "thread/unarchived" => serde_json::from_value(params).map(ServerNotification::ThreadUnarchived),
            "thread/closed" => serde_json::from_value(params).map(ServerNotification::ThreadClosed),
            "thread/reverted" => serde_json::from_value(params).map(ServerNotification::ThreadReverted),
            "skills/changed" => serde_json::from_value(params).map(ServerNotification::SkillsChanged),
            "thread/name/updated" => serde_json::from_value(params).map(ServerNotification::ThreadNameUpdated),
            "thread/attachment/updated" => serde_json::from_value(params).map(ServerNotification::ThreadAttachmentUpdated),
            "thread/goal/updated" => serde_json::from_value(params).map(ServerNotification::ThreadGoalUpdated),
            "thread/goal/cleared" => serde_json::from_value(params).map(ServerNotification::ThreadGoalCleared),
            "thread/queue/changed" => serde_json::from_value(params).map(ServerNotification::ThreadQueueChanged),
            "project/changed" => serde_json::from_value(params).map(ServerNotification::ProjectChanged),
            "thread/project/updated" => serde_json::from_value(params).map(ServerNotification::ThreadProjectUpdated),
            "thread/environment/connected" => serde_json::from_value(params).map(ServerNotification::ThreadEnvironmentConnected),
            "thread/environment/disconnected" => serde_json::from_value(params).map(ServerNotification::ThreadEnvironmentDisconnected),
            "thread/settings/updated" => serde_json::from_value(params).map(ServerNotification::ThreadSettingsUpdated),
            "thread/tokenUsage/updated" => serde_json::from_value(params).map(ServerNotification::ThreadTokenUsageUpdated),
            "turn/started" => serde_json::from_value(params).map(ServerNotification::TurnStarted),
            "hook/started" => serde_json::from_value(params).map(ServerNotification::HookStarted),
            "turn/completed" => serde_json::from_value(params).map(ServerNotification::TurnCompleted),
            "hook/completed" => serde_json::from_value(params).map(ServerNotification::HookCompleted),
            "turn/diff/updated" => serde_json::from_value(params).map(ServerNotification::TurnDiffUpdated),
            "turn/plan/updated" => serde_json::from_value(params).map(ServerNotification::TurnPlanUpdated),
            "item/started" => serde_json::from_value(params).map(ServerNotification::ItemStarted),
            "item/autoApprovalReview/started" => serde_json::from_value(params).map(ServerNotification::ItemAutoApprovalReviewStarted),
            "item/autoApprovalReview/completed" => serde_json::from_value(params).map(ServerNotification::ItemAutoApprovalReviewCompleted),
            "autoApprovalReview/strictReviewRequired" => serde_json::from_value(params).map(ServerNotification::AutoApprovalReviewStrictReviewRequired),
            "item/completed" => serde_json::from_value(params).map(ServerNotification::ItemCompleted),
            "rawResponseItem/completed" => serde_json::from_value(params).map(ServerNotification::RawResponseItemCompleted),
            "rawResponse/completed" => serde_json::from_value(params).map(ServerNotification::RawResponseCompleted),
            "item/agentMessage/delta" => serde_json::from_value(params).map(ServerNotification::ItemAgentMessageDelta),
            "item/plan/delta" => serde_json::from_value(params).map(ServerNotification::ItemPlanDelta),
            "command/exec/outputDelta" => serde_json::from_value(params).map(ServerNotification::CommandExecOutputDelta),
            "process/outputDelta" => serde_json::from_value(params).map(ServerNotification::ProcessOutputDelta),
            "process/exited" => serde_json::from_value(params).map(ServerNotification::ProcessExited),
            "item/commandExecution/outputDelta" => serde_json::from_value(params).map(ServerNotification::ItemCommandExecutionOutputDelta),
            "item/commandExecution/terminalInteraction" => serde_json::from_value(params).map(ServerNotification::ItemCommandExecutionTerminalInteraction),
            "item/fileChange/outputDelta" => serde_json::from_value(params).map(ServerNotification::ItemFileChangeOutputDelta),
            "item/fileChange/patchUpdated" => serde_json::from_value(params).map(ServerNotification::ItemFileChangePatchUpdated),
            "serverRequest/resolved" => serde_json::from_value(params).map(ServerNotification::ServerRequestResolved),
            "item/mcpToolCall/progress" => serde_json::from_value(params).map(ServerNotification::ItemMcpToolCallProgress),
            "mcpServer/oauthLogin/completed" => serde_json::from_value(params).map(ServerNotification::McpServerOauthLoginCompleted),
            "mcpServer/startupStatus/updated" => serde_json::from_value(params).map(ServerNotification::McpServerStartupStatusUpdated),
            "mcpServer/event/stream/notification" => serde_json::from_value(params).map(ServerNotification::McpServerEventStreamNotification),
            "account/updated" => serde_json::from_value(params).map(ServerNotification::AccountUpdated),
            "account/rateLimits/updated" => serde_json::from_value(params).map(ServerNotification::AccountRateLimitsUpdated),
            "app/list/updated" => serde_json::from_value(params).map(ServerNotification::AppListUpdated),
            "remoteControl/status/changed" => serde_json::from_value(params).map(ServerNotification::RemoteControlStatusChanged),
            "externalAgentConfig/import/progress" => serde_json::from_value(params).map(ServerNotification::ExternalAgentConfigImportProgress),
            "externalAgentConfig/import/completed" => serde_json::from_value(params).map(ServerNotification::ExternalAgentConfigImportCompleted),
            "fs/changed" => serde_json::from_value(params).map(ServerNotification::FsChanged),
            "item/reasoning/summaryTextDelta" => serde_json::from_value(params).map(ServerNotification::ItemReasoningSummaryTextDelta),
            "item/reasoning/summaryPartAdded" => serde_json::from_value(params).map(ServerNotification::ItemReasoningSummaryPartAdded),
            "item/reasoning/textDelta" => serde_json::from_value(params).map(ServerNotification::ItemReasoningTextDelta),
            "thread/compacted" => serde_json::from_value(params).map(ServerNotification::ThreadCompacted),
            "model/rerouted" => serde_json::from_value(params).map(ServerNotification::ModelRerouted),
            "model/verification" => serde_json::from_value(params).map(ServerNotification::ModelVerification),
            "modelProvider/authRecoveryStarted" => serde_json::from_value(params).map(ServerNotification::ModelProviderAuthRecoveryStarted),
            "modelProvider/authRecoveryCompleted" => serde_json::from_value(params).map(ServerNotification::ModelProviderAuthRecoveryCompleted),
            "turn/moderationMetadata" => serde_json::from_value(params).map(ServerNotification::TurnModerationMetadata),
            "model/safetyBuffering/updated" => serde_json::from_value(params).map(ServerNotification::ModelSafetyBufferingUpdated),
            "warning" => serde_json::from_value(params).map(ServerNotification::Warning),
            "guardianWarning" => serde_json::from_value(params).map(ServerNotification::GuardianWarning),
            "deprecationNotice" => serde_json::from_value(params).map(ServerNotification::DeprecationNotice),
            "configWarning" => serde_json::from_value(params).map(ServerNotification::ConfigWarning),
            "fuzzyFileSearch/sessionUpdated" => serde_json::from_value(params).map(ServerNotification::FuzzyFileSearchSessionUpdated),
            "fuzzyFileSearch/sessionCompleted" => serde_json::from_value(params).map(ServerNotification::FuzzyFileSearchSessionCompleted),
            "thread/realtime/started" => serde_json::from_value(params).map(ServerNotification::ThreadRealtimeStarted),
            "thread/realtime/itemAdded" => serde_json::from_value(params).map(ServerNotification::ThreadRealtimeItemAdded),
            "thread/realtime/item/started" => serde_json::from_value(params).map(ServerNotification::ThreadRealtimeItemStarted),
            "thread/realtime/item/transcript/delta" => serde_json::from_value(params).map(ServerNotification::ThreadRealtimeItemTranscriptDelta),
            "thread/realtime/item/completed" => serde_json::from_value(params).map(ServerNotification::ThreadRealtimeItemCompleted),
            "thread/realtime/transcript/delta" => serde_json::from_value(params).map(ServerNotification::ThreadRealtimeTranscriptDelta),
            "thread/realtime/transcript/done" => serde_json::from_value(params).map(ServerNotification::ThreadRealtimeTranscriptDone),
            "thread/realtime/outputAudio/delta" => serde_json::from_value(params).map(ServerNotification::ThreadRealtimeOutputAudioDelta),
            "thread/realtime/sdp" => serde_json::from_value(params).map(ServerNotification::ThreadRealtimeSdp),
            "thread/realtime/error" => serde_json::from_value(params).map(ServerNotification::ThreadRealtimeError),
            "thread/realtime/closed" => serde_json::from_value(params).map(ServerNotification::ThreadRealtimeClosed),
            "windows/worldWritableWarning" => serde_json::from_value(params).map(ServerNotification::WindowsWorldWritableWarning),
            "windowsSandbox/setupCompleted" => serde_json::from_value(params).map(ServerNotification::WindowsSandboxSetupCompleted),
            "account/login/completed" => serde_json::from_value(params).map(ServerNotification::AccountLoginCompleted),
            _ => return None,
        })
    }

    /// The params as decoded (keys outside the schema dropped), as JSON.
    pub fn params_value(&self) -> serde_json::Value {
        match self {
            ServerNotification::Error(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadStarted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadStatusChanged(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadArchived(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadDeleted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadUnarchived(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadClosed(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadReverted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::SkillsChanged(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadNameUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadAttachmentUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadGoalUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadGoalCleared(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadQueueChanged(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ProjectChanged(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadProjectUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadEnvironmentConnected(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadEnvironmentDisconnected(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadSettingsUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadTokenUsageUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::TurnStarted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::HookStarted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::TurnCompleted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::HookCompleted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::TurnDiffUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::TurnPlanUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ItemStarted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ItemAutoApprovalReviewStarted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ItemAutoApprovalReviewCompleted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::AutoApprovalReviewStrictReviewRequired(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ItemCompleted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::RawResponseItemCompleted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::RawResponseCompleted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ItemAgentMessageDelta(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ItemPlanDelta(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::CommandExecOutputDelta(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ProcessOutputDelta(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ProcessExited(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ItemCommandExecutionOutputDelta(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ItemCommandExecutionTerminalInteraction(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ItemFileChangeOutputDelta(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ItemFileChangePatchUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ServerRequestResolved(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ItemMcpToolCallProgress(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::McpServerOauthLoginCompleted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::McpServerStartupStatusUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::McpServerEventStreamNotification(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::AccountUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::AccountRateLimitsUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::AppListUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::RemoteControlStatusChanged(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ExternalAgentConfigImportProgress(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ExternalAgentConfigImportCompleted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::FsChanged(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ItemReasoningSummaryTextDelta(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ItemReasoningSummaryPartAdded(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ItemReasoningTextDelta(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadCompacted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ModelRerouted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ModelVerification(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ModelProviderAuthRecoveryStarted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ModelProviderAuthRecoveryCompleted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::TurnModerationMetadata(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ModelSafetyBufferingUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::Warning(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::GuardianWarning(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::DeprecationNotice(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ConfigWarning(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::FuzzyFileSearchSessionUpdated(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::FuzzyFileSearchSessionCompleted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadRealtimeStarted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadRealtimeItemAdded(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadRealtimeItemStarted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadRealtimeItemTranscriptDelta(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadRealtimeItemCompleted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadRealtimeTranscriptDelta(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadRealtimeTranscriptDone(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadRealtimeOutputAudioDelta(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadRealtimeSdp(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadRealtimeError(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::ThreadRealtimeClosed(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::WindowsWorldWritableWarning(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::WindowsSandboxSetupCompleted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerNotification::AccountLoginCompleted(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
        }
    }
}

/// A decoded server request (server → client): one variant per method.
#[derive(Debug, Clone, PartialEq)]
pub enum ServerRequest {
    ItemCommandExecutionRequestApproval(CommandExecutionRequestApprovalParams),
    ItemFileChangeRequestApproval(FileChangeRequestApprovalParams),
    ItemToolRequestUserInput(ToolRequestUserInputParams),
    McpServerElicitationRequest(McpServerElicitationRequestParams),
    ItemPermissionsRequestApproval(PermissionsRequestApprovalParams),
    ItemToolCall(DynamicToolCallParams),
    AccountChatgptAuthTokensRefresh(ChatgptAuthTokensRefreshParams),
    AttestationGenerate(AttestationGenerateParams),
    ApplyPatchApproval(ApplyPatchApprovalParams),
    ExecCommandApproval(ExecCommandApprovalParams),
}

impl ServerRequest {
    pub fn method(&self) -> &'static str {
        match self {
            ServerRequest::ItemCommandExecutionRequestApproval(_) => "item/commandExecution/requestApproval",
            ServerRequest::ItemFileChangeRequestApproval(_) => "item/fileChange/requestApproval",
            ServerRequest::ItemToolRequestUserInput(_) => "item/tool/requestUserInput",
            ServerRequest::McpServerElicitationRequest(_) => "mcpServer/elicitation/request",
            ServerRequest::ItemPermissionsRequestApproval(_) => "item/permissions/requestApproval",
            ServerRequest::ItemToolCall(_) => "item/tool/call",
            ServerRequest::AccountChatgptAuthTokensRefresh(_) => "account/chatgptAuthTokens/refresh",
            ServerRequest::AttestationGenerate(_) => "attestation/generate",
            ServerRequest::ApplyPatchApproval(_) => "applyPatchApproval",
            ServerRequest::ExecCommandApproval(_) => "execCommandApproval",
        }
    }

    /// `None` when the method is not part of the protocol, `Some(Err)` when the params do
    /// not match its schema.
    pub fn decode(method: &str, params: Option<serde_json::Value>) -> Option<Result<Self, serde_json::Error>> {
        let params = params.unwrap_or(serde_json::Value::Null);
        Some(match method {
            "item/commandExecution/requestApproval" => serde_json::from_value(params).map(ServerRequest::ItemCommandExecutionRequestApproval),
            "item/fileChange/requestApproval" => serde_json::from_value(params).map(ServerRequest::ItemFileChangeRequestApproval),
            "item/tool/requestUserInput" => serde_json::from_value(params).map(ServerRequest::ItemToolRequestUserInput),
            "mcpServer/elicitation/request" => serde_json::from_value(params).map(ServerRequest::McpServerElicitationRequest),
            "item/permissions/requestApproval" => serde_json::from_value(params).map(ServerRequest::ItemPermissionsRequestApproval),
            "item/tool/call" => serde_json::from_value(params).map(ServerRequest::ItemToolCall),
            "account/chatgptAuthTokens/refresh" => serde_json::from_value(params).map(ServerRequest::AccountChatgptAuthTokensRefresh),
            "attestation/generate" => serde_json::from_value(params).map(ServerRequest::AttestationGenerate),
            "applyPatchApproval" => serde_json::from_value(params).map(ServerRequest::ApplyPatchApproval),
            "execCommandApproval" => serde_json::from_value(params).map(ServerRequest::ExecCommandApproval),
            _ => return None,
        })
    }

    pub fn params_value(&self) -> serde_json::Value {
        match self {
            ServerRequest::ItemCommandExecutionRequestApproval(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerRequest::ItemFileChangeRequestApproval(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerRequest::ItemToolRequestUserInput(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerRequest::McpServerElicitationRequest(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerRequest::ItemPermissionsRequestApproval(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerRequest::ItemToolCall(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerRequest::AccountChatgptAuthTokensRefresh(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerRequest::AttestationGenerate(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerRequest::ApplyPatchApproval(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
            ServerRequest::ExecCommandApproval(params) => serde_json::to_value(params).unwrap_or(serde_json::Value::Null),
        }
    }
}

/// The response type of each server request.
pub mod server_responses {
    pub type ItemCommandExecutionRequestApproval = super::CommandExecutionRequestApprovalResponse;
    pub type ItemFileChangeRequestApproval = super::FileChangeRequestApprovalResponse;
    pub type ItemToolRequestUserInput = super::ToolRequestUserInputResponse;
    pub type McpServerElicitationRequest = super::McpServerElicitationRequestResponse;
    pub type ItemPermissionsRequestApproval = super::PermissionsRequestApprovalResponse;
    pub type ItemToolCall = super::DynamicToolCallResponse;
    pub type AccountChatgptAuthTokensRefresh = super::ChatgptAuthTokensRefreshResponse;
    pub type AttestationGenerate = super::AttestationGenerateResponse;
    pub type ApplyPatchApproval = super::ApplyPatchApprovalResponse;
    pub type ExecCommandApproval = super::ExecCommandApprovalResponse;
}

/// A client → server request: method name, params and response types.
pub trait ClientRequest {
    const METHOD: &'static str;
    /// False when the method takes no params (`params: undefined`): nothing is sent.
    const HAS_PARAMS: bool;
    type Params: Serialize;
    type Response: serde::de::DeserializeOwned;
}

/// One marker type per client request zenith code sends.
pub mod client_requests {
    use super::*;
    /// `initialize`
    pub enum Initialize {}
    impl ClientRequest for Initialize {
        const METHOD: &'static str = "initialize";
        const HAS_PARAMS: bool = true;
        type Params = InitializeParams;
        type Response = InitializeResponse;
    }
    /// `thread/start`
    pub enum ThreadStart {}
    impl ClientRequest for ThreadStart {
        const METHOD: &'static str = "thread/start";
        const HAS_PARAMS: bool = true;
        type Params = ThreadStartParams;
        type Response = ThreadStartResponse;
    }
    /// `thread/resume`
    pub enum ThreadResume {}
    impl ClientRequest for ThreadResume {
        const METHOD: &'static str = "thread/resume";
        const HAS_PARAMS: bool = true;
        type Params = ThreadResumeParams;
        type Response = ThreadResumeResponse;
    }
    /// `thread/read`
    pub enum ThreadRead {}
    impl ClientRequest for ThreadRead {
        const METHOD: &'static str = "thread/read";
        const HAS_PARAMS: bool = true;
        type Params = ThreadReadParams;
        type Response = ThreadReadResponse;
    }
    /// `thread/turns/list`
    pub enum ThreadTurnsList {}
    impl ClientRequest for ThreadTurnsList {
        const METHOD: &'static str = "thread/turns/list";
        const HAS_PARAMS: bool = true;
        type Params = ThreadTurnsListParams;
        type Response = ThreadTurnsListResponse;
    }
    /// `thread/revert`
    pub enum ThreadRevert {}
    impl ClientRequest for ThreadRevert {
        const METHOD: &'static str = "thread/revert";
        const HAS_PARAMS: bool = true;
        type Params = ThreadRevertParams;
        type Response = ThreadRevertResponse;
    }
    /// `thread/inject_items`
    pub enum ThreadInjectItems {}
    impl ClientRequest for ThreadInjectItems {
        const METHOD: &'static str = "thread/inject_items";
        const HAS_PARAMS: bool = true;
        type Params = ThreadInjectItemsParams;
        type Response = ThreadInjectItemsResponse;
    }
    /// `thread/compact/start`
    pub enum ThreadCompactStart {}
    impl ClientRequest for ThreadCompactStart {
        const METHOD: &'static str = "thread/compact/start";
        const HAS_PARAMS: bool = true;
        type Params = ThreadCompactStartParams;
        type Response = ThreadCompactStartResponse;
    }
    /// `turn/start`
    pub enum TurnStart {}
    impl ClientRequest for TurnStart {
        const METHOD: &'static str = "turn/start";
        const HAS_PARAMS: bool = true;
        type Params = TurnStartParams;
        type Response = TurnStartResponse;
    }
    /// `turn/interrupt`
    pub enum TurnInterrupt {}
    impl ClientRequest for TurnInterrupt {
        const METHOD: &'static str = "turn/interrupt";
        const HAS_PARAMS: bool = true;
        type Params = TurnInterruptParams;
        type Response = TurnInterruptResponse;
    }
    /// `config/mcpServer/reload`
    pub enum ConfigMcpServerReload {}
    impl ClientRequest for ConfigMcpServerReload {
        const METHOD: &'static str = "config/mcpServer/reload";
        const HAS_PARAMS: bool = false;
        type Params = ();
        type Response = McpServerRefreshResponse;
    }
    /// `feedback/upload`
    pub enum FeedbackUpload {}
    impl ClientRequest for FeedbackUpload {
        const METHOD: &'static str = "feedback/upload";
        const HAS_PARAMS: bool = true;
        type Params = FeedbackUploadParams;
        type Response = FeedbackUploadResponse;
    }
    /// `account/read`
    pub enum AccountRead {}
    impl ClientRequest for AccountRead {
        const METHOD: &'static str = "account/read";
        const HAS_PARAMS: bool = true;
        type Params = GetAccountParams;
        type Response = GetAccountResponse;
    }
    /// `account/rateLimits/read`
    pub enum AccountRateLimitsRead {}
    impl ClientRequest for AccountRateLimitsRead {
        const METHOD: &'static str = "account/rateLimits/read";
        const HAS_PARAMS: bool = true;
        type Params = NullableGetAccountRateLimitsParams;
        type Response = GetAccountRateLimitsResponse;
    }
    /// `account/rateLimitResetCredit/consume`
    pub enum AccountRateLimitResetCreditConsume {}
    impl ClientRequest for AccountRateLimitResetCreditConsume {
        const METHOD: &'static str = "account/rateLimitResetCredit/consume";
        const HAS_PARAMS: bool = true;
        type Params = ConsumeAccountRateLimitResetCreditParams;
        type Response = ConsumeAccountRateLimitResetCreditResponse;
    }
    /// `model/list`
    pub enum ModelList {}
    impl ClientRequest for ModelList {
        const METHOD: &'static str = "model/list";
        const HAS_PARAMS: bool = true;
        type Params = ModelListParams;
        type Response = ModelListResponse;
    }
    /// `skills/list`
    pub enum SkillsList {}
    impl ClientRequest for SkillsList {
        const METHOD: &'static str = "skills/list";
        const HAS_PARAMS: bool = true;
        type Params = SkillsListParams;
        type Response = SkillsListResponse;
    }
}
